[connections.mysql]
dialect = "mysql"
host = "191.101.78.99"
port = 3306
database = "iqv-pesquisa"
username = "pma"
password = "kamisama123"

[connections.mysql_2]
dialect = "mysql"
host = "prod-dev.myscriptcase.com"
port = 3306
database = "proddevm_saude"
username = "proddevm_samuel"
password = "Gayzao123"