[connections.mysql]
dialect = "mysql"
host = "185.192.96.99"
port = 3306
database = "iqv-pesquisa"
username = "tcc_samuel"
password = "XO4E8i"

[connections.mysql_2]
dialect = "mysql"
host = "prod-dev.myscriptcase.com"
port = 3306
database = "proddevm_saude"
username = "proddevm_samuel"
password = "Gayzao123"